LaboDos/Models/AlmacenPersona.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboDos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlmacenPersonaEntities : DbContext
    {
        public AlmacenPersonaEntities()
            : base("name=AlmacenPersonaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}

LaboDos/Models/AlmacenPersona.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\Users\USER\Documents\GitHub\LaboDos\LaboDos\Models\AlmacenPersona.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

LaboDos/Models/AlmacenPersona.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

LaboDos/Models/Persona.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboDos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        public int IdPersona { get; set; }

        [Display(Name = "NombrePersona ")]
        [Required(ErrorMessage = "estos campos son requeridos")]
        public string NombrePersona { get; set; }


        [Display(Name = "Edad")]
        [Required(ErrorMessage = "estos campos son requeridos")]
        [Range(18, 100, ErrorMessage = "El campo {0} debe estar entre los números {1} y {2}")]
        public Nullable<int> EdadPersona { get; set; }

        [Display(Name = "DescripcionPersona ")]
        [Required(ErrorMessage = "estos campos son requeridos")]
        public string DescripcionPersona { get; set; }
    }
}

LaboDos/Models/ViewModel/PersonaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LaboDos.Models.ViewModel
{
    public class PersonaViewModel
    {
        public int IdPersona { get; set; }

        [Display(Name = "Nombre ")]
        [Required(ErrorMessage = "estos campos son requeridos")]
        public string NombrePersona { get; set; }

        [Range(18, 100, ErrorMessage = "El campo {0} debe estar entre los números {1} y {2}")]
        [Display(Name = "Edad")]
        [Required(ErrorMessage = "estos campos son requeridos")]
        public Nullable<int> EdadPersona { get; set; }

        [Display(Name = "Descripcion ")]
        [Required(ErrorMessage = "estos campos son requeridos")]
        public string DescripcionPersona { get; set; }
    }
}

LaboDos/Models/sysdiagrams.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboDos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagrams
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}

LaboDos/Controllers/HomeController.cs
using LaboDos.Models;
using LaboDos.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LaboDos.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

            // //Persona persona = new Persona();
            // PersonaRepository personaRepository = new PersonaRepository();
            // //persona.NombrePersona = "Progra apli 1";
            // //persona.EdadPersona = 15;
            // //persona.DescripcionPersona = "persona adulta altura promedio";
            // //personaRepository.Save(persona);

            //var  ListOfData = personaRepository.ListDataPersona();

            // return View(ListOfData); //razor page nos adactara

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LaboDos/Controllers/RegistroController.cs
using LaboDos.Models;
using LaboDos.Models.ViewModel;
using LaboDos.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LaboDos.Controllers
{
    public class RegistroController : Controller
    {
        // GET: Registro
        public ActionResult Registrar()
        {

            //Persona persona = new Persona();
            //PersonaRepository personaRepository = new PersonaRepository();
            //persona.NombrePersona = "Progra apli 1";
            //persona.EdadPersona = 15;
            //persona.DescripcionPersona = "persona adulta altura promedio";
            //personaRepository.Save(persona);

            //var ListOfData = personaRepository.ListDataPersona();

            return View(); //razor page nos adactara


        }
        public ActionResult Registrars(PersonaViewModel personas)
        {
          
            if (ModelState.IsValid)
            {   
                return View("Registrar",personas);
            }
           else 
                return View("Registros");
             

        }
        public ActionResult Registro ()
        {
            return View ();
        }

        public ActionResult Registros(Persona personas)
        {           
            PersonaRepository personaRepository = new PersonaRepository();

            personaRepository.Save(personas);

            var ListOfData = personaRepository.ListDataPersona();

            return View(ListOfData); //razor page nos adactara
        }       
    }
}

LaboDos/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LaboDos/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LaboDos/Views/Home/Index.cshtml
@model List<LaboDos.Models.Persona>


@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="container">
        <table class="table success" id="tabladeregistros">
            <thead>
            <th>
                IdPersona
            </th>
            <th>
                Nombre
            </th>
            <th>
                Edad
            </th>
            <th>
                Descripcion
            </th>

            </thead>
            <tbody>

                @foreach (var item in Model)
                {

                    <tr>

                        <td>@item.IdPersona </td>
                        <td>@item.NombrePersona </td>
                        <td>@item.EdadPersona </td>
                        <td>@item.DescripcionPersona </td>

                    </tr>


                }


            </tbody>



        </table>
    </div>
   
    

LaboDos/Views/Registro/Registrar.cshtml
@model  LaboDos.Models.ViewModel.PersonaViewModel
@{
    ViewBag.Title = "Registrar";
}

@using (Html.BeginForm("Registros", "Registro", FormMethod.Post))
{
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    </head>
    <body>

        <div class="animate__animated animate__backInDown">

            <h2>Registro</h2>
            <br />
            @Html.LabelFor(m => m.NombrePersona)
            <br />
            @Html.TextBoxFor(m => m.NombrePersona)
            <br />
            @Html.ValidationMessageFor(m => m.NombrePersona)
            <br />
            @Html.LabelFor(m => m.EdadPersona)
            <br />
            @Html.TextBoxFor(m => m.EdadPersona, new { type = "number" })
            <br />
            @Html.ValidationMessageFor(m => m.EdadPersona, null)
            <br />
            @Html.LabelFor(m => m.DescripcionPersona)
            <br />
            @Html.TextBoxFor(m => m.DescripcionPersona)
            <br />
            @Html.ValidationMessageFor(m => m.DescripcionPersona, null)
            <br />
            <input type="submit" class="btn btn-default" />
        </div>
    </body>
</html>


}




@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

LaboDos/Views/Registro/Registros.cshtml
@model List<LaboDos.Models.Persona>
@{
    ViewBag.Title = "Registros";
}

<h2>Registros</h2>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
</head>
<body>

    <div class="row">
        <div class="container">
            <div class="animate__animated animate__fadeInDown">
                <table class="table table-hover" id="tabladeregistros">
                    <thead>
                    <th>
                        IdPersona
                    </th>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Edad
                    </th>
                    <th>
                        Descripcion
                    </th>

                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {

                            <tr>

                                <td>@item.IdPersona </td>
                                <td>@item.NombrePersona </td>
                                <td>@item.EdadPersona </td>
                                <td>@item.DescripcionPersona </td>

                            </tr>


                        }


                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>

LaboDos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>